import React, {useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Sparkles, Search, ChevronDown, MapPin, Users, Car, Network, Zap, ArrowUpRight, Play, Check, Route, Calendar, Plus, ChevronRight, CircleDot, Gauge, Send, Repeat2, X, Moon, Sun} from 'lucide-react';
import './styles.css';

const communities={
  nst:{name:'Newton School of Technology',city:'Bengaluru',tag:'Student community',size:'2,840',scan:'1,126',accent:'#ff6b3d',areas:['HSR Layout','Bellandur','Marathahalli'],event:'Product & Pizza · Friday',activity:'High'},
  iit:{name:'IIT Delhi',city:'New Delhi',tag:'Campus community',size:'8,210',scan:'2,418',accent:'#7c65ff',areas:['Hauz Khas','Saket','Lajpat Nagar'],event:'Rendezvous · Saturday',activity:'Very high'},
  microsoft:{name:'Microsoft',city:'Bengaluru',tag:'Workplace community',size:'4,650',scan:'1,842',accent:'#0078d4',areas:['Indiranagar','HSR Layout','Whitefield'],event:'Hack night · Thursday',activity:'High'},
  koramangala:{name:'Koramangala Residents',city:'Bengaluru',tag:'Residential community',size:'6,120',scan:'1,781',accent:'#f4a826',areas:['Koramangala','HSR Layout','BTM Layout'],event:'Sunday market · Sunday',activity:'Medium'}
};
const basePeople=[
 {id:1,name:'Ananya Rao',initials:'AR',role:'Community Champion',loc:'HSR Layout',activity:92,reach:184,score:96,kind:'champion',detail:'Runs the NST Women in Tech circle and is organizing this week’s Product & Pizza. Her group overlaps with 3 commute clusters.',signal:'Event organiser + 3 overlapping groups',intervention:'Give Ananya a host link for the Friday event'},
 {id:2,name:'Rohit Mehta',initials:'RM',role:'Potential Driver',loc:'Bellandur',activity:78,reach:61,score:91,kind:'driver',detail:'Drives from Bellandur to campus 4 days a week. His route crosses the highest passenger-density corridor.',signal:'Repeated Bellandur → HSR commute pattern',intervention:'Offer a 3-seat first-ride challenge'},
 {id:3,name:'Priya Nair',initials:'PN',role:'Connector',loc:'Marathahalli',activity:88,reach:143,score:89,kind:'connector',detail:'Active across the placement, design, and hostel communities. Trusted peer who can turn an invitation into a group action.',signal:'143 reachable peers across 4 active communities',intervention:'Invite Priya to coordinate her cohort'},
 {id:4,name:'Arjun Kapoor',initials:'AK',role:'Early Adopter',loc:'HSR Layout',activity:84,reach:76,score:86,kind:'early',detail:'Regularly tries campus tools and has asked about shared travel before. Likely to bring a friend after first match.',signal:'Early adopter behavior + weekly event attendance',intervention:'Offer a bring-a-friend ride credit'},
 {id:5,name:'Sneha Iyer',initials:'SI',role:'Potential Passenger',loc:'Bellandur',activity:69,reach:33,score:82,kind:'passenger',detail:'Commutes to campus on the Bellandur route 5 days a week and engages with late-evening event posts.',signal:'High route demand + event attendance',intervention:'Invite to Friday’s coordinated ride'},
 {id:6,name:'Vikram Shah',initials:'VS',role:'Potential Driver',loc:'Koramangala',activity:63,reach:48,score:78,kind:'driver',detail:'Owns a 5-seat car and has a flexible work schedule. His route can support a second commute cluster.',signal:'Available seats on matching route',intervention:'Activate after the first Bellandur match'},
 {id:7,name:'Ishita Bose',initials:'IB',role:'Potential Passenger',loc:'HSR Layout',activity:73,reach:42,score:76,kind:'passenger',detail:'Frequent community participant who lives within 800m of the HSR pickup point.',signal:'Close to pickup + active in cohort group',intervention:'Send a nearby-seat invitation'},
 {id:8,name:'Karan Malhotra',initials:'KM',role:'Connector',loc:'Bellandur',activity:72,reach:109,score:74,kind:'connector',detail:'Maintains the alumni WhatsApp community and often helps coordinate informal meetups.',signal:'109-person alumni micro-network',intervention:'Ask for a ride-pool introduction'}
];
const sources=[['in','LinkedIn','NST student & alumni graph','468 relevant profiles'],['◐','Reddit','r/bangalore student threads','18 commute conversations'],['◈','Events','Public event calendar','2 high-attendance events'],['⌁','Geo signals','Campus & commute corridors','3 matching clusters']];
function App(){
 const [community,setCommunity]=useState('nst'),[scanned,setScanned]=useState(false),[scanning,setScanning]=useState(false),[filter,setFilter]=useState('All'),[selected,setSelected]=useState(basePeople[0]),[interventions,setInterventions]=useState([false,false,false]),[ride,setRide]=useState(0),[joined,setJoined]=useState(0),[growth,setGrowth]=useState(0),[notice,setNotice]=useState(''),[dark,setDark]=useState(false);
 const c=communities[community]; const activated=interventions.filter(Boolean).length; const active=7+activated*3+ride*5+joined*2+growth*4; const progress=[['Connector',1],['Drivers',3],['Passengers',8],['Rides',5],['Referrals',14],['Active users',31]];
 const people=useMemo(()=>basePeople.map((p,i)=>({...p,score:Math.max(64,p.score-(community==='iit'?i%2:0))})),[community]);
 const filtered=filter==='All'?people:people.filter(p=>p.role.includes(filter));
 function scan(){setScanning(true); setTimeout(()=>{setScanning(false);setScanned(true);setNotice('Scan complete — 4 high-confidence opportunities found.');},1200)}
 function activate(i){setInterventions(a=>a.map((x,idx)=>idx===i?!x:x));setNotice(interventions[i]?'Intervention paused.':'Intervention activated — the activation plan is now live.');}
 function createRide(){if(!ride){setRide(1);setNotice('Ride FR-001 created. Invite the nearby passengers to fill its seats.')}else setNotice('FR-001 is already active.')}
 function joinRide(){if(!ride){setNotice('Create the first ride before inviting passengers.');return} if(joined<3){setJoined(j=>j+1);setNotice(`Passenger joined FR-001 — ${3-(joined+1)} seats remain.`)}else setNotice('FR-001 is full. A second route is ready to activate.')}
 function resetCommunity(id){setCommunity(id);setScanned(false);setScanning(false);setFilter('All');setSelected(basePeople[0]);setInterventions([false,false,false]);setRide(0);setJoined(0);setGrowth(0);setNotice('Community changed. Run a scan to uncover local signals.');}
 return <div className={'app '+(dark?'dark':'')} style={{'--accent':c.accent}}>
  <aside className="sidebar"><div className="brand"><div className="brandmark"><Route size={18}/></div><span>fellaride</span></div><div className="workspace"><span>ACTIVATION WORKSPACE</span><b>Community intelligence</b><small>Find the first momentum.</small></div><nav>{[['Overview',Gauge],['Discovery',Search],['People',Users],['Interventions',Zap],['Ride studio',Car],['Growth loop',Repeat2]].map(([x,I],i)=><a className={i===0?'active':''} href={'#'+x.replace(' ','-')} key={x}><I size={17}/>{x}{i===2&&<em>8</em>}</a>)}</nav><div className="side-bottom"><div className="sim"><span className="pulse"></span>SIMULATION</div><p>Private prototype · Mock signals only</p></div></aside>
  <main><header><div className="crumb"><span>Communities</span><ChevronRight size={14}/><b>{c.name}</b></div><div className="header-actions"><button className="help">How it works</button><button className="iconbtn" aria-label="Search"><Search size={18}/></button><button className="theme-toggle" aria-label={dark?'Switch to light theme':'Switch to dark theme'} onClick={()=>setDark(v=>!v)}>{dark?<Sun size={16}/>:<Moon size={16}/>}</button><div className="avatar">AK</div></div></header>
   <section className="hero" id="Overview"><div className="hero-top"><div className="community-switch"><button onClick={()=>document.getElementById('community-menu').classList.toggle('show')}><span className="place-dot"></span>{c.name}<span className="city">{c.city}</span><ChevronDown size={15}/></button><div id="community-menu" className="community-menu">{Object.entries(communities).map(([id,x])=><button key={id} onClick={()=>{resetCommunity(id);document.getElementById('community-menu').classList.remove('show')}}>{x.name}<small>{x.city}</small></button>)}</div></div><span className="status-pill"><span></span>{scanned?'Community ready':'Awaiting discovery'}</span></div>
    <div className="hero-stage"><div className="hero-copy"><div className="eyebrow"><Sparkles size={13}/> FELLARIDE INTELLIGENCE</div><h1>{scanned?<>Your community is<br/><i>ready to activate.</i></>:<>Find the moment that<br/><i>starts the movement.</i></>}</h1><p>{scanned?'Three people and one shared moment could unlock the first twenty riders.':'We’ll connect social trust, shared routes, and timely moments into a first ride plan.'}</p>{!scanned?<button className={'primary hero-cta '+(scanning?'loading':'')} onClick={scan}>{scanning?'Looking for momentum…':'Discover activation opportunities'} {!scanning&&<ArrowUpRight size={16}/>}</button>:<button className="primary hero-cta" onClick={()=>document.getElementById('People').scrollIntoView({behavior:'smooth'})}>Meet the first three people <ArrowUpRight size={16}/></button>}</div>
    <div className="next-card"><div className="next-label"><span>RECOMMENDED NEXT STEP</span><span className="num">01</span></div><div className="next-avatar"><div className="person-avatar champion">AR</div><div className="avatar-orbit one"></div><div className="avatar-orbit two"></div></div><h3>{scanned?'Start with Ananya’s Friday event.':'Run a community scan.'}</h3><p>{scanned?'Her community circle, Friday’s event, and the Bellandur corridor align around one easy first ask.':'We’ll find social connectors, recurring commute routes, and moments where a first ride feels natural.'}</p><button className="text-button" onClick={()=>scanned?document.getElementById('Interventions').scrollIntoView({behavior:'smooth'}):scan()}>{scanned?'View activation plan':'Start discovery'} <ChevronRight size={15}/></button></div></div>
   <div className="stats"><Metric icon={<Users/>} label="COMMUNITY SIGNALS" value={scanned?c.scan:'—'} sub={scanned?'strong public footprint':'scan to uncover'} /><Metric icon={<Network/>} label="PEOPLE TO START WITH" value={scanned?'3':'—'} sub={scanned?'reach 388 peers together':'social gravity matters'} /><Metric icon={<Route/>} label="STRONGEST ROUTE" value={scanned?'94%':'—'} sub={scanned?'Bellandur → campus':'waiting for a signal'} /><Metric icon={<Zap/>} label="COMMUNITY MOMENTUM" value={scanned?'High':'Quiet'} sub={scanned?'best window: Friday':'one action away'} /></div></section>
   {notice&&<div className="notice"><Sparkles size={16}/>{notice}<button onClick={()=>setNotice('')}><X size={15}/></button></div>}
   <section className="section scan" id="Discovery"><div className="section-head"><div><span className="kicker">01 / DISCOVER</span><h2>The community, in context.</h2><p>Signals from public spaces are synthesized into local activation opportunities.</p></div><button className={'primary '+(scanning?'loading':'')} onClick={scan}>{scanning?'Scanning public signals…':scanned?'Refresh community scan':'Run community scan'} {!scanning&&<ArrowUpRight size={16}/>}</button></div>
   <div className="discovery-grid"><div className="source-grid">{sources.map(([ico,name,desc,num],i)=><div className={'source-card '+(!scanned?'muted':'')} key={name}><div className="source-icon">{ico}</div><div><b>{name}</b><p>{desc}</p></div><strong>{scanned?num:'—'}</strong></div>)}</div><div className={'insight-card '+(!scanned?'pre-scan':'')}><div className="ai-label"><Sparkles size={14}/> FELLARIDE INTELLIGENCE</div>{scanned?<><h3>One corridor is ready first.</h3><p><b>Bellandur → NST campus</b> has the clearest match surface: 42 likely passengers, 11 possible drivers, and a shared Friday event.</p><div className="tags"><span>42 passengers</span><span>11 drivers</span><span>Fri 6:30 PM</span></div></>:<><h3>What will we look for?</h3><p>Shared routes, social trust, upcoming moments, and the people able to turn interest into a first ride.</p></>}</div></div></section>
   <section className="section people-section" id="People"><div className="section-head compact"><div><span className="kicker">02 / PRIORITIZE</span><h2>Start with social gravity.</h2></div><div className="filters">{['All','Driver','Passenger','Connector','Early','Champion'].map(f=><button className={filter===f?'selected':''} onClick={()=>setFilter(f)} key={f}>{f}</button>)}</div></div>
   <div className="people-layout"><div className="people-list">{filtered.map(p=><button className={'person '+(selected.id===p.id?'chosen':'')} onClick={()=>setSelected(p)} key={p.id}><div className={'person-avatar '+p.kind}>{p.initials}</div><div className="person-main"><b>{p.name}</b><span>{p.role} · {p.loc}</span></div><div className="score"><b>{p.score}</b><small>impact</small></div></button>)}</div><div className="person-detail"><div className="detail-top"><div className={'person-avatar large '+selected.kind}>{selected.initials}</div><div><span className="role-pill">{selected.role}</span><h3>{selected.name}</h3><p><MapPin size={13}/>{selected.loc}</p></div></div><div className="why"><span>WHY THIS PERSON MATTERS</span><p>{selected.detail}</p></div><div className="mini-metrics"><div><b>{selected.reach}</b><small>reachable peers</small></div><div><b>{selected.activity}%</b><small>community activity</small></div><div><b>{selected.score}</b><small>activation score</small></div></div><div className="signal"><Sparkles size={15}/><span><b>Leading signal</b>{selected.signal}</span></div><button className="outline" onClick={()=>setNotice(`${selected.name} added to the activation queue.`)}>Add to activation queue <Plus size={16}/></button></div></div></section>
   <section className="section interventions" id="Interventions"><div className="section-head compact"><div><span className="kicker">03 / ACTIVATE</span><h2>Make the ask feel native.</h2><p>Context beats promotion. Choose the moment, then turn intent into a coordinated action.</p></div><span className="live-count">{activated} LIVE</span></div><div className="intervention-grid">{[
    ['Upcoming moment',Calendar,'Product & Pizza · Friday',`23 members are already going. Offer a coordinated ride home while the group is together.`,'Create an event ride room'],
    ['Commute cluster',Route,'Bellandur → NST',`42 potential passengers and 11 drivers overlap on this corridor. Start with two drivers.`,'Activate 2 driver hosts'],
    ['Community connector',Network,'Ananya’s Women in Tech circle',`A trusted host can make the first ride feel like a group plan, not a new app.`,'Give Ananya a host link']
   ].map(([type,Icon,title,text,cta],i)=><article className={'intervention '+(interventions[i]?'live':'')} key={title}><div className="int-top"><span>{type}</span><Icon size={20}/></div><h3>{title}</h3><p>{text}</p><button onClick={()=>activate(i)}>{interventions[i]?<><Check size={15}/> Live now</>:<><Play size={14}/>{cta}</>} </button></article>)}</div></section>
   <section className="section commute" id="Ride-studio"><div className="section-head compact"><div><span className="kicker">04 / MATCH</span><h2>Find the highest-probability ride.</h2></div><div className="route-chip"><CircleDot size={14}/> Bellandur → NST campus</div></div><div className="commute-grid"><div className="map"><div className="map-label label-a"><b>Bellandur</b><span>42 demand</span></div><div className="map-label label-b"><b>HSR Layout</b><span>27 demand</span></div><div className="map-label label-c"><b>NST Campus</b><span>destination</span></div><svg viewBox="0 0 600 300"><path d="M70 220 C190 270, 260 60, 495 92"/><path className="minor" d="M165 250 C280 170, 325 160, 495 92"/><circle cx="70" cy="220" r="10"/><circle cx="495" cy="92" r="10"/></svg><div className="map-legend"><span className="dot"></span> high matching potential</div></div><div className="match-panel"><div className="match-score"><span>ROUTE MATCH SCORE</span><b>94<span>/100</span></b><p>Best starting route in this community</p></div><div className="route-data"><div><span>Potential passengers</span><b>42</b></div><div><span>Available drivers</span><b>{11+activated}</b></div><div><span>Seats in first wave</span><b>{ride?3-joined:9}</b></div></div><button className="primary full" onClick={createRide}>{ride?<><Check size={16}/> Ride FR-001 created</>:<><Car size={16}/> Create first ride</>}</button>{ride&&<button className="outline full join" onClick={joinRide}><Users size={16}/> Invite nearby passenger ({joined}/3 joined)</button>}</div></div></section>
   <section className="section growth" id="Growth-loop"><div className="growth-copy"><span className="kicker">05 / COMPOUND</span><h2>Let the first ride<br/>do the selling.</h2><p>Every successful match creates social proof, referrals, and enough density for the next ride.</p><button className="primary" onClick={()=>{setGrowth(g=>g+1);setNotice('Growth loop advanced — new referrals and repeat riders added.')}}><Repeat2 size={16}/> Simulate next loop</button></div><div className="loop"><div className="loop-line"></div>{progress.map(([x,n],i)=>{const val=i===0?1:i===1?Math.min(3,1+activated):i===2?Math.min(8,2+joined*2+activated):i===3?ride?Math.min(5,1+growth):0:i===4?growth*4+joined*2:i===5?active:0;return <div className={'loop-step '+(val?'lit':'')} key={x}><span>{x}</span><b>{val}</b>{i<progress.length-1&&<ChevronDown size={15}/>}</div>})}</div></section>
   <section className="section analytics"><div className="section-head compact"><div><span className="kicker">ACTIVATION ANALYTICS</span><h2>From signal to repeat behavior.</h2></div><span className="updated">LIVE SIMULATION</span></div><div className="funnel">{[['Community members',c.size],['Potential users',scanned?268:0],['Prioritized users',scanned?8:0],['Engaged users',activated*5],['Registered users',active],['Ride participants',joined+(ride?1:0)],['Repeat users',growth*2],['Referrals',growth*4+joined*2]].map(([x,v],i)=><div className="funnel-row" key={x}><span>{String(i+1).padStart(2,'0')}</span><b>{x}</b><div><i style={{width:`${Math.max(4,Math.min(100,Number(v)/28))}%`}}></i></div><strong>{v}</strong></div>)}</div></section>
  </main></div>
}
function Metric({icon,label,value,sub}){return <div className="metric"><div className="metric-icon">{icon}</div><div><span>{label}</span><b>{value}</b><small>{sub}</small></div></div>}
createRoot(document.getElementById('root')).render(<App/>);
